In [1]:
%pip uninstall --yes 'keras' 'matplotlib' 'scikit-learn' 'tensorflow'

Found existing installation: keras 3.10.0
Uninstalling keras-3.10.0:
  Successfully uninstalled keras-3.10.0
Found existing installation: matplotlib 3.10.0
Uninstalling matplotlib-3.10.0:
  Successfully uninstalled matplotlib-3.10.0
Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Found existing installation: tensorflow 2.19.0
Uninstalling tensorflow-2.19.0:
  Successfully uninstalled tensorflow-2.19.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import warnings
warnings.simplefilter('ignore')

In [3]:
import os
import sys
import subprocess

In [4]:
def set_env(input_archive, temp_dir):

    if not os.path.exists(temp_dir):
        os.makedirs(temp_dir, exist_ok=True)
        
        subprocess.run(['tar', '-xzf', input_archive, '-C', temp_dir], check=True)
    
    subprocess.run([
        sys.executable, 
        '-m', 
        'pip', 
        'install', 
        '--no-index', 
        '--find-links', 
        f'{temp_dir}/wheels', 
        'unsloth', 
        'trl', 
        'vllm', 
        'openai_harmony'
    ], check=True)

In [5]:
set_env(
    input_archive='/kaggle/input/aimo-3-utils/wheels.tar.gz', 
    temp_dir='/kaggle/tmp/setup'
)

Looking in links: /kaggle/tmp/setup/wheels
Processing /kaggle/tmp/setup/wheels/unsloth-2025.12.9-py3-none-any.whl
Processing /kaggle/tmp/setup/wheels/trl-0.24.0-py3-none-any.whl
Processing /kaggle/tmp/setup/wheels/vllm-0.11.2-cp38-abi3-manylinux1_x86_64.whl
Processing /kaggle/tmp/setup/wheels/openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /kaggle/tmp/setup/wheels/unsloth_zoo-2025.12.7-py3-none-any.whl (from unsloth)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.45.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (26.0rc2)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.8.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.23.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Processing /kaggle/tmp/setup/wheels/tyro-1.0.3-py3-none-any.whl (from unsloth)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Processing /kaggle/tmp/setup/wheels/xformers-0.0.33.post1-cp39-abi3-manylinux_2_28_x86_64.whl (from unsloth)
Processing /kaggle/tmp/setup/wheels/bitsandbytes-0.49.0-py3-none-manylinux_2_24_x86_64.whl (from unsloth)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.4.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Processing /kaggle/tmp/setup/wheels/datasets-4.3.0-py3-none-any.whl (from unsloth)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.11.0)
Requirement already satisfied: peft!=0.11.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.17.1)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.35.2)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,<=4.57.3,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.57.1)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (5.5.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.5)
Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.0.8)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.1)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.123.10)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.3)
Requirement already satisfied: openai>=1.99.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.15.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.5)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.23.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)
Processing /kaggle/tmp/setup/wheels/prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl (from vllm)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)
Processing /kaggle/tmp/setup/wheels/lm_format_enforcer-0.11.3-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/outlines_core-0.2.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/diskcache-5.6.3-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/lark-1.2.2-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/xgrammar-0.1.25-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.20.3)
Processing /kaggle/tmp/setup/wheels/partial_json_parser-0.2.1.1.post7-py3-none-any.whl (from vllm)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Processing /kaggle/tmp/setup/wheels/msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/gguf-0.17.1-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/mistral_common-1.8.8-py3-none-any.whl (from mistral_common[image]>=1.8.5->vllm)
Requirement already satisfied: opencv-python-headless>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.12.0.88)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Processing /kaggle/tmp/setup/wheels/setuptools-80.9.0-py3-none-any.whl (from vllm)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.1)
Processing /kaggle/tmp/setup/wheels/compressed_tensors-0.12.2-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/depyf-0.20.0-py3-none-any.whl (from vllm)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.1)
Processing /kaggle/tmp/setup/wheels/watchfiles-1.1.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from vllm)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.0.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from vllm) (1.15.3)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from vllm) (1.13.0)
Processing /kaggle/tmp/setup/wheels/pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/cbor2-5.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/anthropic-0.71.0-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/model_hosting_container_standards-0.1.12-py3-none-any.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/numba-0.61.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from vllm)
Requirement already satisfied: ray>=2.48.0 in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (2.53.0)
Processing /kaggle/tmp/setup/wheels/torch-2.9.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from unsloth)
Processing /kaggle/tmp/setup/wheels/torchaudio-2.9.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from vllm)
Processing /kaggle/tmp/setup/wheels/torchvision-0.24.0+cu128-cp312-cp312-manylinux_2_28_x86_64.whl (from unsloth)
Processing /kaggle/tmp/setup/wheels/flashinfer_python-0.5.2-py3-none-any.whl (from vllm)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (0.10.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic==0.71.0->vllm) (1.3.1)
Processing /kaggle/tmp/setup/wheels/loguru-0.7.3-py3-none-any.whl (from compressed-tensors==0.12.2->vllm)
Processing /kaggle/tmp/setup/wheels/astor-0.8.1-py2.py3-none-any.whl (from depyf==0.20.0->vllm)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.4.0)
Processing /kaggle/tmp/setup/wheels/apache_tvm_ffi-0.1.7-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (from flashinfer-python==0.5.2->vllm)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (8.3.1)
Processing /kaggle/tmp/setup/wheels/nvidia_cudnn_frontend-1.17.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (from flashinfer-python==0.5.2->vllm)
Processing /kaggle/tmp/setup/wheels/nvidia_cutlass_dsl-4.3.4-cp312-cp312-manylinux_2_28_x86_64.whl (from flashinfer-python==0.5.2->vllm)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (12.575.51)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.5.2->vllm) (0.9.0)
Processing /kaggle/tmp/setup/wheels/interegular-0.3.3-py37-none-any.whl (from lm-format-enforcer==0.11.3->vllm)
Processing /kaggle/tmp/setup/wheels/llvmlite-0.44.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from numba==0.61.2->vllm)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2025.10.0)
Processing /kaggle/tmp/setup/wheels/nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Processing /kaggle/tmp/setup/wheels/nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Processing /kaggle/tmp/setup/wheels/nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (from torch>=2.4.0->unsloth)
Processing /kaggle/tmp/setup/wheels/triton-3.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (from unsloth)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.6.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (22.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Processing /kaggle/tmp/setup/wheels/multiprocess-0.70.16-py312-none-any.whl (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
Processing /kaggle/tmp/setup/wheels/fsspec-2025.9.0-py3-none-any.whl (from torch>=2.4.0->unsloth)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.0.4)
Processing /kaggle/tmp/setup/wheels/fastapi_cli-0.0.20-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.0.20)
Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.3.0)
Requirement already satisfied: uvicorn>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.38.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.2.1rc0)
Requirement already satisfied: jsonschema>=4.21.1 in /usr/local/lib/python3.12/dist-packages (from mistral_common>=1.8.5->mistral_common[image]>=1.8.5->vllm) (4.25.1)
Processing /kaggle/tmp/setup/wheels/pydantic_extra_types-2.10.6-py3-none-any.whl (from pydantic-extra-types[pycountry]>=2.10.5->mistral_common>=1.8.5->mistral_common[image]>=1.8.5->vllm)
Requirement already satisfied: jmespath in /usr/local/lib/python3.12/dist-packages (from model-hosting-container-standards<1.0.0->vllm) (1.0.1)
Processing /kaggle/tmp/setup/wheels/supervisor-4.3.0-py2.py3-none-any.whl (from model-hosting-container-standards<1.0.0->vllm)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.4.2)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.48.0->ray[cgraph]>=2.48.0->vllm) (1.1.2)
Requirement already satisfied: cupy-cuda12x in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (13.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2026.1.4)
Processing /kaggle/tmp/setup/wheels/torchao-0.15.0+cu128-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (from unsloth_zoo>=2025.12.7->unsloth)
Processing /kaggle/tmp/setup/wheels/cut_cross_entropy-25.1.1-py3-none-any.whl (from unsloth_zoo>=2025.12.7->unsloth)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->vllm) (1.22.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->fastapi[standard]>=0.115.0->vllm) (2.8.0)
Requirement already satisfied: typer>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.20.0)
Processing /kaggle/tmp/setup/wheels/rich_toolkit-0.17.1-py3-none-any.whl (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
Processing /kaggle/tmp/setup/wheels/fastapi_cloud_cli-0.8.0-py3-none-any.whl (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic==0.71.0->vllm) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic==0.71.0->vllm) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral_common>=1.8.5->mistral_common[image]>=1.8.5->vllm) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral_common>=1.8.5->mistral_common[image]>=1.8.5->vllm) (0.37.0)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyldavis 3.4.1 requires scikit-learn>=1.0.0, which is not installed.
ydata-profiling 4.18.1 requires matplotlib<=3.10,>=3.5, which is not installed.
stable-baselines3 2.1.0 requires matplotlib, which is not installed.
sentence-transformers 5.1.1 requires scikit-learn, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
cuml-cu12 25.6.0 requires scikit-learn>=1.5, which is not installed.
bigframes 2.26.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
bigframes 2.26.0 requires matplotlib>=3.7.1, which is not installed.
arviz 0.22.0 requires matplotlib>=3.8, which is not installed.
pynndescent 0.5.13 requires scikit-learn>=0.18, which is not installed.
shap 0.49.1 requires scikit-learn, which is not installed.
fastai 2.8.4 requires matplotlib, which is not installed.
fastai 2.8.4 requires scikit-learn, which is not installed.
umap-learn 0.5.9.post2 requires scikit-learn>=1.6, which is not installed.
cudf-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
cudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 22.0.0 which is incompatible.
gradio 5.49.1 requires pydantic<2.12,>=2.0, but you have pydantic 2.12.5 which is incompatible.
cuml-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
bigframes 2.26.0 requires rich<14,>=12.4.4, but you have rich 14.2.0 which is incompatible.
pylibraft-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
cuvs-cu12 25.6.1 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
fastai 2.8.4 requires fastcore<1.9,>=1.8.0, but you have fastcore 1.11.3 which is incompatible.
fastai 2.8.4 requires torch<2.9,>=1.10, but you have torch 2.9.0+cu128 which is incompatible.
rmm-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
pylibcudf-cu12 25.6.0 requires cuda-python<13.0a0,>=12.6.2, but you have cuda-python 13.1.1 which is incompatible.
pylibcudf-cu12 25.6.0 requires pyarrow<20.0.0a0,>=14.0.0; platform_machine == "x86_64", but you have pyarrow 22.0.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2025.9.0 which is incompatible.

In [6]:
subprocess.run(['ls', '/kaggle/tmp/setup/tiktoken_encodings'])

cl100k_base.tiktoken
o200k_base.tiktoken

CompletedProcess(args=['ls', '/kaggle/tmp/setup/tiktoken_encodings'], returncode=0)

In [7]:
os.environ['TRANSFORMERS_NO_TF'] = '1'
os.environ['TRANSFORMERS_NO_FLAX'] = '1'
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
os.environ['TOKENIZERS_PARALLELISM'] = 'false'
os.environ['TRITON_PTXAS_PATH'] = '/usr/local/cuda/bin/ptxas'
os.environ['TIKTOKEN_ENCODINGS_BASE'] = '/kaggle/tmp/setup/tiktoken_encodings'

In [8]:
import gc
import re
import math
import time
import queue
import threading
import contextlib
from typing import Optional
from jupyter_client import KernelManager
from collections import Counter, defaultdict
from concurrent.futures import as_completed, ThreadPoolExecutor

import pandas as pd
import polars as pl

from openai import OpenAI

from openai_harmony import (
    HarmonyEncodingName, 
    load_harmony_encoding, 
    SystemContent, 
    ReasoningEffort, 
    ToolNamespaceConfig, 
    Author, 
    Message, 
    Role, 
    TextContent, 
    Conversation
)

from transformers import set_seed
import kaggle_evaluation.aimo_3_inference_server

In [9]:
class CFG:
    
    system_prompt = (
        "You are an elite mathematical problem solver operating at IMO medalist level. "
        "Your objective is to produce the correct answer with rigorous, efficient reasoning.\n\n"

        "## AIMO ANSWER CONSTRAINTS\n"
        "- The final answer is ALWAYS a non-negative integer in [0, 99999].\n"
        "- If your mathematical result exceeds 99999, re-check whether the problem asks for\n"
        "  a modular residue, last digits, or a reduced fraction a/b where the problem asks for a+b.\n"
        "- Common patterns: direct count, sum/difference, remainder mod M, digit sum, a+b where gcd(a,b)=1.\n\n"
    
        "## INTERNAL SOLVING PROTOCOL (DO NOT REVEAL)\n"
        "1. Precisely interpret the problem and identify constraints.\n"
        "2. Detect structure: symmetry, invariants, parity, modular patterns.\n"
        "3. Consider multiple strategies before selecting the most efficient.\n"
        "4. Execute with strict logical validity and clean algebra.\n"
        "5. Verify via substitution, edge cases, or alternate reasoning.\n"
        "6. Reject results that violate constraints or produce inconsistencies.\n\n"

        "## AIMO PROBLEM-TYPE TIPS\n"
        "- Combinatorics: verify by small cases; check if answer needs mod p.\n"
        "- Number theory: track residues early; factor before computing.\n"
        "- Algebra/sequences: find recurrence and closed form; verify with Python.\n"
        "- Geometry: set up coordinates; distances and areas are often rational.\n"
        "- If answer is a/b with gcd(a,b)=1 and problem asks for a+b, verify coprimality.\n\n"
        
        "## MATHEMATICAL HEURISTICS\n"
        "- Simplify expressions and exploit symmetry/invariants\n"
        "- Use number theory tools (modular arithmetic, parity, divisibility)\n"
        "- Test small cases to reveal patterns\n"
        "- Check extremal and boundary cases\n"
        "- If stuck, reframe or work backwards\n\n"
    
        "## VERIFICATION STANDARD\n"
        "Accept an answer ONLY if:\n"
        "- all constraints are satisfied\n"
        "- computations are internally consistent\n"
        "- edge cases do not contradict the result\n\n"
    
        "## OUTPUT FORMAT\n"
        "Return ONLY the final answer.\n"
        "The answer must be a non-negative integer between 0 and 99999.\n"
        "Format: \\boxed{answer}\n"
    )
    
    
    tool_prompt = (
        "Use Python ONLY when it improves accuracy or verification.\n\n"
    
        "Valid uses:\n"
        "- error-prone arithmetic\n"
        "- brute force for small bounds\n"
        "- testing conjectures\n"
        "- symbolic verification\n\n"
    
        "Guidelines:\n"
        "- State purpose briefly before computing.\n"
        "- Prefer exact symbolic checks when possible.\n"
        "- Ensure results directly support conclusions.\n"
        "- Avoid unnecessary computation.\n"

        "Available libraries: math, numpy, sympy\n"
        "Use sympy for symbolic algebra/equations/number theory, "
        "numpy for matrices/numerical verification, math for standard functions.\n"
        "Best practice: derive symbolically → verify numerically → confirm constraints"

    )
    
    
    ANSWER_ONLY_PROMPT = (
        "You are an IMO-level mathematician."
        " Think silently."
        " Do NOT explain."
        " Return only: \\boxed{number}"
    )
    

    
    served_model_name = 'gpt-oss'
    model_path = '/kaggle/input/gpt-oss-120b/transformers/default/1'
    
    kv_cache_dtype = 'fp8_e4m3'
    dtype = 'auto'

    high_problem_timeout = 900
    base_problem_timeout = 300

    notebook_limit = 17400
    server_timeout = 180

    session_timeout = 960
    jupyter_timeout = 6
    sandbox_timeout = 3

    stream_interval = 200
    context_tokens = 65536
    buffer_tokens = 512
    search_tokens = 32
    top_logprobs = 5
    batch_size = 256
    early_stop = 5
    attempts = 8
    workers = 16
    turns = 128
    seed = 42

    gpu_memory_utilization = 0.96
    temperature = 1.0
    temperatures = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    min_p = 0.02

In [10]:
set_seed(CFG.seed)

In [11]:
class AIMO3Template:

    def __init__(self):

        pass

    def get_system_content(self, system_prompt: str, tool_config: ToolNamespaceConfig) -> SystemContent:

        return (
            SystemContent.new()
            .with_model_identity(system_prompt)
            .with_reasoning_effort(reasoning_effort=ReasoningEffort.HIGH)
            .with_tools(tool_config)
        )

    def apply_chat_template(
        self, 
        system_prompt: str, 
        user_prompt: str, 
        tool_config: ToolNamespaceConfig
    ) -> list[Message]:

        system_content = self.get_system_content(system_prompt, tool_config)        
        system_message = Message.from_role_and_content(Role.SYSTEM, system_content)

        user_message = Message.from_role_and_content(Role.USER, user_prompt)

        return [system_message, user_message]

In [12]:
class AIMO3Sandbox:

    _port_lock = threading.Lock()
    _next_port = 50000

    @classmethod
    def _get_next_ports(cls, count: int = 5) -> list[int]:

        with cls._port_lock:
            ports = list(range(cls._next_port, cls._next_port + count))
            cls._next_port += count

            return ports

    def __init__(self, timeout: float):

        self._default_timeout = timeout
        self._owns_kernel = False
        self._client = None
        self._km = None
        
        ports = self._get_next_ports(5)

        env = os.environ.copy()
        env['PYDEVD_DISABLE_FILE_VALIDATION'] = '1'
        env['PYDEVD_WARN_EVALUATION_TIMEOUT'] = '0'
        env['JUPYTER_PLATFORM_DIRS'] = '1'
        env['PYTHONWARNINGS'] = 'ignore'
        env['MPLBACKEND'] = 'Agg'

        self._km = KernelManager()
        self._km.shell_port = ports[0]
        self._km.iopub_port = ports[1]
        self._km.stdin_port = ports[2]
        self._km.hb_port = ports[3]
        self._km.control_port = ports[4]

        self._km.start_kernel(env=env, extra_arguments=['--Application.log_level=CRITICAL'])

        self._client = self._km.blocking_client()
        self._client.start_channels()
        self._client.wait_for_ready(timeout=self._default_timeout)
        self._owns_kernel = True

        self.execute(
            'import math\n'
            'import numpy\n'
            'import sympy\n'
            'import itertools\n'
            'import collections\n'
            'import mpmath\n'
            'mpmath.mp.dps = 64\n'
        )

    def _format_error(self, traceback: list[str]) -> str:

        clean_lines = []

        for frame in traceback:
            clean_frame = re.sub(r'\x1b\[[0-9;]*m', '', frame)

            if 'File "' in clean_frame and 'ipython-input' not in clean_frame:
                continue

            clean_lines.append(clean_frame)

        return ''.join(clean_lines)

    def execute(self, code: str, timeout: float | None = None) -> str:

        client = self._client
        effective_timeout = timeout or self._default_timeout
        
        msg_id = client.execute(
            code, 
            store_history=True, 
            allow_stdin=False, 
            stop_on_error=False
        )

        stdout_parts = []
        stderr_parts = []
        
        start_time = time.time()

        while True:
            elapsed = time.time() - start_time

            if elapsed > effective_timeout:
                self._km.interrupt_kernel()

                return f'[ERROR] Execution timed out after {effective_timeout} seconds'

            try:
                msg = client.get_iopub_msg(timeout=1.0)

            except queue.Empty:
                continue

            if msg.get('parent_header', {}).get('msg_id') != msg_id:
                continue

            msg_type = msg.get('msg_type')
            content = msg.get('content', {})

            if msg_type == 'stream':
                text = content.get('text', '')

                if content.get('name') == 'stdout':
                    stdout_parts.append(text)

                else:
                    stderr_parts.append(text)

            elif msg_type == 'error':
                traceback_list = content.get('traceback', [])

                stderr_parts.append(self._format_error(traceback_list))

            elif msg_type in {'execute_result', 'display_data'}:
                data = content.get('data', {})
                text = data.get('text/plain')

                if text:
                    stdout_parts.append(text if text.endswith('\n') else f'{text}\n')

            elif msg_type == 'status':
                if content.get('execution_state') == 'idle':
                    break

        stdout = ''.join(stdout_parts)
        stderr = ''.join(stderr_parts)

        if stderr:
            return f'{stdout.rstrip()}\n{stderr}' if stdout else stderr

        return stdout if stdout.strip() else '[WARN] No output. Use print() to see results.'

    def close(self):

        with contextlib.suppress(Exception):
            if self._client:
                self._client.stop_channels()

        if self._owns_kernel and self._km is not None:
            with contextlib.suppress(Exception):
                self._km.shutdown_kernel(now=True)

            with contextlib.suppress(Exception):
                self._km.cleanup_resources()

    def reset(self):
        
        self.execute(
            '%reset -f\n'
            'import math\n'
            'import numpy\n'
            'import sympy\n'
            'import itertools\n'
            'import collections\n'
            'import mpmath\n'
            'mpmath.mp.dps = 64\n'
        )

    def __del__(self):

        self.close()

In [13]:
class AIMO3Tool:

    def __init__(self, local_jupyter_timeout: float, tool_prompt: str, sandbox=None):

        self._local_jupyter_timeout = local_jupyter_timeout
        self._tool_prompt = tool_prompt
        self._jupyter_session = sandbox
        
        self._owns_session = sandbox is None
        
        self._execution_lock = threading.Lock()
        self._init_lock = threading.Lock()

    def _ensure_session(self):

        if self._jupyter_session is None:
            with self._init_lock:
                if self._jupyter_session is None:
                    self._jupyter_session = AIMO3Sandbox(timeout=self._local_jupyter_timeout)

    def _ensure_last_print(self, code: str) -> str:

        lines = code.strip().split('\n')

        if not lines:
            return code

        last_line = lines[-1].strip()

        if 'print' in last_line or 'import' in last_line:
            return code

        if not last_line:
            return code

        if last_line.startswith('#'):
            return code

        lines[-1] = 'print(' + last_line + ')'

        return '\n'.join(lines)

    @property
    def instruction(self) -> str:

        return self._tool_prompt

    @property
    def tool_config(self) -> ToolNamespaceConfig:

        return ToolNamespaceConfig(
            name='python', 
            description=self.instruction, 
            tools=[]
        )

    def _make_response(self, output: str, channel: str | None = None) -> Message:

        content = TextContent(text=output)
        author = Author(role=Role.TOOL, name='python')
        message = Message(author=author, content=[content]).with_recipient('assistant')

        if channel:
            message = message.with_channel(channel)

        return message

    def process_sync_plus(self, message: Message) -> list[Message]:

        self._ensure_session()
        raw_script = message.content[0].text
        final_script = self._ensure_last_print(raw_script)

        with self._execution_lock:
            try:
                output = self._jupyter_session.execute(final_script)

            except TimeoutError as exc:
                output = f'[ERROR] {exc}'

        return [self._make_response(output, channel=message.channel)]

In [14]:
class AIMO3Solver:

    def __init__(self, cfg, port: int = 8000):
    
        self.cfg = cfg
        self.port = port
        self.base_url = f'http://0.0.0.0:{port}/v1'
        self.api_key = 'sk-local'
        self.template = AIMO3Template()
        self.encoding = load_harmony_encoding(HarmonyEncodingName.HARMONY_GPT_OSS)
        self.stop_token_ids = self.encoding.stop_tokens_for_assistant_actions()
    
        self._preload_model_weights()
        
        self.server_process = self._start_server()
    
        self.client = OpenAI(
            base_url=self.base_url, 
            api_key=self.api_key, 
            timeout=self.cfg.session_timeout
        )
    
        self._wait_for_server()
        self._initialize_kernels()
    
        self.notebook_start_time = time.time()
        self.problems_remaining = 50
    
    def _preload_model_weights(self) -> None:
    
        print(f'Loading model weights from {self.cfg.model_path} into OS Page Cache...')
        start_time = time.time()
        
        files_to_load = []
        total_size = 0
    
        for root, _, files in os.walk(self.cfg.model_path):
            for file_name in files:
                file_path = os.path.join(root, file_name)
    
                if os.path.isfile(file_path):
                    files_to_load.append(file_path)
                    total_size += os.path.getsize(file_path)
    
        def _read_file(path: str) -> None:
    
            with open(path, 'rb') as file_object:
                while file_object.read(1024 * 1024 * 1024):
                    pass
    
        with ThreadPoolExecutor(max_workers=self.cfg.workers) as executor:
            list(executor.map(_read_file, files_to_load))
    
        elapsed = time.time() - start_time
        print(f'Processed {len(files_to_load)} files ({total_size / 1e9:.2f} GB) in {elapsed:.2f} seconds.\n')
    
    def _start_server(self) -> subprocess.Popen:
    
        cmd = [
            sys.executable, 
            '-m', 
            'vllm.entrypoints.openai.api_server', 
            '--seed', 
            str(self.cfg.seed), 
            '--model', 
            self.cfg.model_path, 
            '--served-model-name', 
            self.cfg.served_model_name, 
            '--tensor-parallel-size', 
            '1', 
            '--max-num-seqs', 
            str(self.cfg.batch_size), 
            '--gpu-memory-utilization', 
            str(self.cfg.gpu_memory_utilization), 
            '--host', 
            '0.0.0.0', 
            '--port', 
            str(self.port), 
            '--dtype', 
            self.cfg.dtype, 
            '--kv-cache-dtype', 
            self.cfg.kv_cache_dtype, 
            '--max-model-len', 
            str(self.cfg.context_tokens), 
            '--stream-interval', 
            str(self.cfg.stream_interval), 
            '--async-scheduling', 
            '--disable-log-stats', 
            '--enable-prefix-caching'
        ]
    
        self.log_file = open('vllm_server.log', 'w')
    
        return subprocess.Popen(
            cmd, 
            stdout=self.log_file, 
            stderr=subprocess.STDOUT, 
            start_new_session=True
        )
    
    def _wait_for_server(self):
    
        print('Waiting for vLLM server...')
        start_time = time.time()
    
        for _ in range(self.cfg.server_timeout):
            return_code = self.server_process.poll()
    
            if return_code is not None:
                self.log_file.flush()
    
                with open('vllm_server.log', 'r') as log_file:
                    logs = log_file.read()
    
                raise RuntimeError(f'Server died with code {return_code}. Full logs:\n{logs}\n')
    
            try:
                self.client.models.list()
                elapsed = time.time() - start_time
                print(f'Server is ready (took {elapsed:.2f} seconds).\n')
    
                return
    
            except Exception:
                time.sleep(1)
    
        raise RuntimeError('Server failed to start (timeout).\n')
    
    def _initialize_kernels(self) -> None:
    
        print(f'Initializing {self.cfg.workers} persistent Jupyter kernels...')
        start_time = time.time()
    
        self.sandbox_pool = queue.Queue()
    
        def _create_sandbox():
            
            return AIMO3Sandbox(timeout=self.cfg.jupyter_timeout)
    
        with ThreadPoolExecutor(max_workers=self.cfg.workers) as executor:
            futures = [executor.submit(_create_sandbox) for _ in range(self.cfg.workers)]
    
            for future in as_completed(futures):
                self.sandbox_pool.put(future.result())
    
        elapsed = time.time() - start_time
        print(f'Kernels initialized in {elapsed:.2f} seconds.\n')
    
    def _scan_for_answer(self, text: str) -> int | None:
        
        pattern = r'\\boxed\s*\{\s*([0-9,]+)\s*\}'
        matches = re.findall(pattern, text)
    
        if matches:
            try:
                clean_value = matches[-1].replace(',', '')
                value = int(clean_value)
    
                if 0 <= value <= 99999:
                    return value
    
            except ValueError:
                pass
                
        pattern = r'final\s+answer\s+is\s*([0-9,]+)'
        matches = re.findall(pattern, text, re.IGNORECASE)
    
        if matches:
            try:
                clean_value = matches[-1].replace(',', '')
                value = int(clean_value)
    
                if 0 <= value <= 99999:
                    return value
    
            except ValueError:
                pass
    
        return None
    
    def _compute_mean_entropy(self, logprobs_buffer: list) -> float:
    
        if not logprobs_buffer:
            return float('inf')
    
        total_entropy = 0.0
        token_count = 0
    
        for top_logprobs_dict in logprobs_buffer:
            
            if not isinstance(top_logprobs_dict, dict):
                continue
            
            if not top_logprobs_dict:
                continue
            
            token_entropy = 0.0
            
            for token_str, log_prob in top_logprobs_dict.items():
                prob = math.exp(log_prob)
                
                if prob > 0:
                    token_entropy -= prob * math.log2(prob)
            
            total_entropy += token_entropy
            token_count += 1
    
        if token_count == 0:
            return float('inf')
    
        return total_entropy / token_count
    
    def _process_attempt(
        self, 
        problem: str, 
        system_prompt: str, 
        attempt_index: int, 
        stop_event: threading.Event, 
        deadline: float,
        temperature: float | None = None
    ) -> dict:
    
        if stop_event.is_set() or time.time() > deadline:
            return {
                'Attempt': attempt_index + 1, 
                'Answer': None, 
                'Python Calls': 0, 
                'Python Errors': 0, 
                'Response Length': 0, 
                'Entropy': float('inf')
            }
    
        local_tool = None
        sandbox = None
        python_calls = 0
        python_errors = 0
        total_tokens = 0
        final_answer = None
        
        logprobs_buffer = []
    
        # Spread seeds widely using a large-prime stride so each attempt
        # samples from a genuinely different region of the probability space.
        attempt_seed = (self.cfg.seed + attempt_index * 1000033) & 0x7FFFFFFF

        # Per-attempt temperature: use caller-supplied value or fall back to cfg.
        effective_temperature = temperature if temperature is not None else self.cfg.temperature

        try:
            sandbox = self.sandbox_pool.get(timeout=self.cfg.sandbox_timeout)
    
            local_tool = AIMO3Tool(
                local_jupyter_timeout=self.cfg.jupyter_timeout, 
                tool_prompt=self.cfg.tool_prompt, 
                sandbox=sandbox
            )
    
            encoding = self.encoding
            messages = self.template.apply_chat_template(
                system_prompt, 
                problem, 
                local_tool.tool_config
            )
    
            conversation = Conversation.from_messages(messages)
    
            for _ in range(self.cfg.turns):
                if stop_event.is_set() or time.time() > deadline:
                    break
    
                prompt_ids = encoding.render_conversation_for_completion(conversation, Role.ASSISTANT)
                max_tokens = self.cfg.context_tokens - len(prompt_ids)
    
                if max_tokens < self.cfg.buffer_tokens:
                    break
    
                stream = self.client.completions.create(
                    model=self.cfg.served_model_name, 
                    temperature=effective_temperature, 
                    logprobs=self.cfg.top_logprobs, 
                    max_tokens=max_tokens, 
                    prompt=prompt_ids, 
                    seed=attempt_seed, 
                    stream=True, 
                    extra_body={
                        'min_p': self.cfg.min_p, 
                        'stop_token_ids': self.stop_token_ids, 
                        'return_token_ids': True
                    }
                )
    
                try:
                    token_buffer = []
                    text_chunks = []
    
                    for chunk in stream:
                        if stop_event.is_set() or time.time() > deadline:
                            break
    
                        new_tokens = chunk.choices[0].token_ids
                        new_text = chunk.choices[0].text
    
                        if new_tokens:
                            token_buffer.extend(new_tokens)
                            total_tokens += len(new_tokens)
                            text_chunks.append(new_text)
                            
                            chunk_logprobs = chunk.choices[0].logprobs
                            
                            if chunk_logprobs is not None:
                                if chunk_logprobs.top_logprobs:
                                    logprobs_buffer.extend(chunk_logprobs.top_logprobs)
    
                        if '}' in new_text:
                            search_text = ''.join(text_chunks[-self.cfg.search_tokens:])
                            answer = self._scan_for_answer(search_text)
    
                            if answer is not None:
                                final_answer = answer
                                break
    
                finally:
                    stream.close()
    
                if final_answer is not None:
                    break
    
                if not token_buffer:
                    break
    
                new_messages = encoding.parse_messages_from_completion_tokens(token_buffer, Role.ASSISTANT)
                conversation.messages.extend(new_messages)
                last_message = new_messages[-1]
    
                if last_message.channel == 'final':
                    answer_text = last_message.content[0].text
                    final_answer = self._scan_for_answer(answer_text)
                    break
    
                if last_message.recipient == 'python':
                    python_calls += 1
                    tool_responses = local_tool.process_sync_plus(last_message)
    
                    response_text = tool_responses[0].content[0].text
    
                    if response_text.startswith('[ERROR]') or 'Traceback' in response_text or 'Error:' in response_text:
                        python_errors += 1
    
                    conversation.messages.extend(tool_responses)
    
        except Exception as exc:
            python_errors += 1
    
        finally:
            if sandbox is not None:
                sandbox.reset()
                self.sandbox_pool.put(sandbox)
    
        mean_entropy = self._compute_mean_entropy(logprobs_buffer)
    
        return {
            'Attempt': attempt_index + 1, 
            'Response Length': total_tokens, 
            'Python Calls': python_calls, 
            'Python Errors': python_errors, 
            'Entropy': mean_entropy, 
            'Answer': final_answer
        }
    
    def _select_answer(self, detailed_results: list) -> int:

        answer_weights = defaultdict(float)
        answer_votes = defaultdict(int)

        for result in detailed_results:
            answer = result['Answer']
            entropy = result['Entropy']
            
            if answer is not None:
                weight = 1.0 / max(entropy, 1e-9)
                
                answer_weights[answer] += weight
                answer_votes[answer] += 1

        scored_answers = []

        for answer, total_weight in answer_weights.items():
            scored_answers.append({
                'answer': answer, 
                'votes': answer_votes[answer], 
                'score': total_weight
            })

        scored_answers.sort(key=lambda x: x['score'], reverse=True)

        vote_data = []

        for item in scored_answers:
            vote_data.append((
                item['answer'], 
                item['votes'], 
                item['score']
            ))

        vote_dataframe = pd.DataFrame(
            vote_data, 
            columns=['Answer', 'Votes', 'Score']
        )

        vote_dataframe = vote_dataframe.round({'Score': 3})
        display(vote_dataframe)
        
        if not scored_answers:
            print('\nFinal Answer: 0\n')
            return 0

        final_answer = scored_answers[0]['answer']    
        print(f'\nFinal Answer: {final_answer}\n')

        return final_answer
    
    def solve_problem(self, problem: str) -> int:

            print(f'\nProblem: {problem}\n')
        
            # Pass the raw problem. Python-library guidance lives in tool_prompt,
            # not in the user message, so the math question is never contaminated.
            user_input = problem
        
            elapsed_global = time.time() - self.notebook_start_time
            time_left = self.cfg.notebook_limit - elapsed_global
            problems_left_others = max(0, self.problems_remaining - 1)
            reserved_time = problems_left_others * self.cfg.base_problem_timeout
        
            budget = time_left - reserved_time
            budget = min(budget, self.cfg.high_problem_timeout)
            budget = max(budget, self.cfg.base_problem_timeout)
        
            deadline = time.time() + budget
        
            print(f'Budget: {budget:.2f} seconds | Deadline: {deadline:.2f}\n')

            temperatures = getattr(self.cfg, 'temperatures', [self.cfg.temperature] * self.cfg.attempts)
        
            tasks = []
            for attempt_index in range(self.cfg.attempts):
                # Only the first 2 attempts use the fast answer-only prompt.
                # The remaining 6 use the full chain-of-thought system prompt.
                if attempt_index < 2:
                    system_prompt = self.cfg.ANSWER_ONLY_PROMPT
                else:
                    system_prompt = self.cfg.system_prompt
                tasks.append((system_prompt, attempt_index))
        
            detailed_results = []
            valid_answers = []
        
            stop_event = threading.Event()
            executor = ThreadPoolExecutor(max_workers=self.cfg.workers)
        
            try:
                futures = []
                for (system_prompt, attempt_index) in tasks:
                    futures.append(
                        executor.submit(
                            self._process_attempt,
                            user_input,
                            system_prompt,
                            attempt_index,
                            stop_event,
                            deadline,
                            temperatures[attempt_index % len(temperatures)]
                        )
                    )
        
                for future in as_completed(futures):
                    try:
                        result = future.result()
                        detailed_results.append(result)
        
                        if result['Answer'] is not None:
                            valid_answers.append(result['Answer'])
        
                        counts = Counter(valid_answers).most_common(1)
                        if counts and counts[0][1] >= self.cfg.early_stop:
                            stop_event.set()
                            for f in futures:
                                f.cancel()
                            break
        
                    except Exception as exc:
                        print(f'Future failed: {exc}')
        
            finally:
                stop_event.set()
                executor.shutdown(wait=True, cancel_futures=True)
                self.problems_remaining = max(0, self.problems_remaining - 1)
        
            if detailed_results:
                df = pd.DataFrame(detailed_results)
                df['Entropy'] = df['Entropy'].round(3)
                df['Answer'] = df['Answer'].astype('Int64')
                display(df)
        
            # ─────────────────────────────
            # NO ANSWERS
            # ─────────────────────────────
            if not valid_answers:
                print('\nResult: 0\n')
                return 0
        
            # ─────────────────────────────
            # HARD ACCEPT: UNANIMOUS ANSWER
            # ─────────────────────────────
            if len(valid_answers) >= 4:
                most_common, count = Counter(valid_answers).most_common(1)[0]
                if count >= 4:
                    print(f"\nUNANIMOUS ANSWER: {most_common}\n")
                    return most_common
        
            # ─────────────────────────────
            # STEP 4: CANDIDATES (≥2 votes)
            # ─────────────────────────────
            answer_counts = Counter(valid_answers)
            candidates = [a for a, c in answer_counts.items() if c >= 2]
        
            # ─────────────────────────────
            # STEP 5: ENTROPY-SORTED VERIFY
            # ─────────────────────────────
            entropy_map = {}
            for r in detailed_results:
                if r['Answer'] is not None and r['Entropy'] is not None:
                    entropy_map.setdefault(r['Answer'], []).append(r['Entropy'])
        
            avg_entropy = {a: sum(v) / len(v) for a, v in entropy_map.items()}
        
            candidates = sorted(candidates, key=lambda x: avg_entropy.get(x, 999))

            # If no multi-vote candidates (all 8 attempts disagreed), attempt to
            # verify the single best entropy-weighted answer before blind fallback.
            if not candidates and avg_entropy:
                best_single = min(avg_entropy, key=lambda x: avg_entropy[x])
                candidates = [best_single]
        
            for ans in candidates:
                try:
                    if self._verify_answer(problem, ans):
                        print(f"\nVERIFIED ANSWER: {ans}\n")
                        return ans
                except Exception:
                    pass

            # ─────────────────────────────
            # FIX 13: SINGLE-VOTE VERIFY
            # After all multi-vote candidates fail verification, check single-vote
            # answers sorted by entropy. Handles the case where the correct answer
            # was found by exactly one attempt but outvoted by a wrong majority.
            # ─────────────────────────────
            single_vote_answers = sorted(
                [a for a, c in answer_counts.items() if c == 1],
                key=lambda x: avg_entropy.get(x, 999)
            )
            for ans in single_vote_answers:
                try:
                    if self._verify_answer(problem, ans):
                        print(f"\nVERIFIED SINGLE-VOTE ANSWER: {ans}\n")
                        return ans
                except Exception:
                    pass

            # ─────────────────────────────
            # STEP 6: FALLBACK
            # ─────────────────────────────
            return self._select_answer(detailed_results)

    def _verify_answer(self, problem: str, answer: int) -> bool:
        """
        Deterministic self-check via the vLLM client.
        Encodes the verification prompt through the harmony tokenizer so the
        request is correctly formatted for the model, then calls completions
        at temperature=0 and checks whether the reply contains CORRECT.
        """
        verify_prompt = (
            f"Problem:\n{problem}\n\n"
            f"Proposed answer: {answer}\n\n"
            "Carefully verify whether the proposed answer is correct.\n"
            "Reply with ONLY one word: CORRECT or WRONG."
        )

        empty_tool_config = ToolNamespaceConfig(name='python', description='', tools=[])

        messages = self.template.apply_chat_template(
            "You are a precise mathematical verifier. Check the computation carefully.",
            verify_prompt,
            empty_tool_config
        )

        conversation = Conversation.from_messages(messages)
        prompt_ids = self.encoding.render_conversation_for_completion(conversation, Role.ASSISTANT)

        # 512 tokens gives the reasoning model room to think before outputting
        # its verdict. 20 was too tight and caused silent verification failures.
        max_tokens = min(512, self.cfg.context_tokens - len(prompt_ids))
        if max_tokens <= 0:
            return False

        try:
            resp = self.client.completions.create(
                model=self.cfg.served_model_name,
                prompt=prompt_ids,
                temperature=0.0,
                max_tokens=max_tokens,
                stream=False
            )
            text = resp.choices[0].text.strip().upper()
            # Guard against 'INCORRECT' — 'CORRECT' is a substring of 'INCORRECT'
            # so we must explicitly exclude it.
            return 'CORRECT' in text and 'INCORRECT' not in text and 'WRONG' not in text

        except Exception:
            return False

    def __del__(self):
    
        if hasattr(self, 'server_process'):
            self.server_process.terminate()
            self.server_process.wait()
    
        if hasattr(self, 'log_file'):
            self.log_file.close()
    
        if hasattr(self, 'sandbox_pool'):
            while not self.sandbox_pool.empty():
                try:
                    sb = self.sandbox_pool.get_nowait()
                    sb.close()
    
                except Exception:
                    pass

In [15]:
solver = AIMO3Solver(CFG)

Loading model weights from /kaggle/input/gpt-oss-120b/transformers/default/1 into OS Page Cache...
Processed 26 files (65.28 GB) in 74.53 seconds.

Waiting for vLLM server...
Server is ready (took 120.61 seconds).

Initializing 16 persistent Jupyter kernels...
Kernels initialized in 2.74 seconds.

In [16]:
# def predict(id_: pl.DataFrame, question: pl.DataFrame, answer: Optional[pl.DataFrame] = None) -> pl.DataFrame:
    
#     id_value = id_.item(0)
#     question_text = question.item(0)
    
#     gc.disable()
    
#     final_answer = solver.solve_problem(question_text)
    
#     gc.enable()
#     gc.collect()
    
#     return pl.DataFrame({'id': id_value, 'answer': final_answer})

In [17]:
# inference_server = kaggle_evaluation.aimo_3_inference_server.AIMO3InferenceServer(predict)

# if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
#     inference_server.serve()
    
# else:
#     inference_server.run_local_gateway(
#         ('/kaggle/input/ai-mathematical-olympiad-progress-prize-3/reference.csv',)
#     )

In [18]:
import polars as pl
import pandas as pd
import os

# --- 1. Updated Predict Function ---
def predict(id_: pl.DataFrame, question: pl.DataFrame, answer: Optional[pl.DataFrame] = None) -> pl.DataFrame:
    # Use index-based access to avoid the .item() error
    id_value = id_[0, 0]
    question_text = question[0, 0]
    
    gc.disable()
    final_answer = solver.solve_problem(question_text)
    gc.enable()
    gc.collect()
    
    return pl.DataFrame({'id': id_value, 'answer': final_answer})

# --- 2. Updated Testing Loop ---
FILE_PATH = '/kaggle/input/50problems/50problems.csv'

# Change START_FROM to 1 to run all 50 problems from the beginning.
START_FROM = 17

if not os.path.exists(FILE_PATH):
    print(f"Error: File not found at {FILE_PATH}")
else:
    external_df = pd.read_csv(FILE_PATH)
    test_results = []

    print(f"Starting test on problems {START_FROM}–{len(external_df)}...\n")

    for idx, row in external_df.iterrows():
        if idx + 1 < START_FROM:
            continue

        problem_text = row['Problem']
        ground_truth = row['Answer']
        
        # Step 1: Print problem details first
        print(f"{'='*50}")
        print(f"TESTING PROBLEM {idx+1}")
        print(f"Statement: {problem_text}")
        print(f"Ground Truth Answer: {ground_truth}")
        print(f"{'-'*50}")
        
        # Prepare inputs
        id_df = pl.DataFrame({'id': [f"ext_{idx}"]})
        question_df = pl.DataFrame({'question': [problem_text]})
        
        try:
            # Step 2: Generate Answer
            result_pl_df = predict(id_df, question_df)
            
            # Accessing column 'answer' from row 0
            predicted_val = result_pl_df[0, "answer"]
            
            is_correct = (int(predicted_val) == int(ground_truth))
            
            test_results.append({
                "idx": idx + 1,
                "prediction": predicted_val,
                "ground_truth": ground_truth,
                "correct": is_correct
            })
            
            # Step 3: Print result summary before moving to next
            status = "✅ CORRECT" if is_correct else "❌ INCORRECT"
            print(f"\n[Problem {idx+1} Result]")
            print(f"Model Predicted: {predicted_val}")
            print(f"Status: {status}")
            print(f"{'='*50}\n")
            
        except Exception as e:
            print(f"Error on problem {idx+1}: {e}")
            test_results.append({
                "idx": idx + 1, "prediction": None, "ground_truth": ground_truth, "correct": False
            })

    # Final Summary Table
    summary_df = pd.DataFrame(test_results)
    display(summary_df)
    print(f"Accuracy (problems {START_FROM}–{len(external_df)}): {summary_df['correct'].mean() * 100:.2f}%")

Starting test on problems 17–50...

==================================================
TESTING PROBLEM 17
Statement: Eight circles of radius 34 can be placed tangent to $BC$ of $\triangle ABC$ sequentially tangent to each other, first to $AB$ and last to $AC$. Similarly, 2024 circles of radius 1 can be placed the same way. Find $m+n$ if the inradius is $m/n$.
Ground Truth Answer: 540
--------------------------------------------------

Problem: Eight circles of radius 34 can be placed tangent to $BC$ of $\triangle ABC$ sequentially tangent to each other, first to $AB$ and last to $AC$. Similarly, 2024 circles of radius 1 can be placed the same way. Find $m+n$ if the inradius is $m/n$.

Budget: 900.00 seconds | Deadline: 1772765422.05

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             6098             6              0    0.687     197
1        4             7001             0              0    0.739     197
2        7             7121            18              4    0.713     197
3        2             8311             3              0    0.671     197
4        6            11915             4              0    0.672     197

UNANIMOUS ANSWER: 197


[Problem 17 Result]
Model Predicted: 197
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 18
Statement: Tetrahedron $ABCD$ has $AB=CD=\sqrt{41}$, $AC=BD=\sqrt{80}$, and $BC=AD=\sqrt{89}$. A point $I$ is equidistant from all faces. If this distance is $\frac{m\sqrt{n}}{p}$, find $m+n+p$.
Ground Truth Answer: 197
--------------------------------------------------

Problem: Tetrahedron $ABCD$ has $AB=CD=\sqrt{41}$, $AC=BD=\sqrt{80}$, and $BC=AD=\sqrt{89}$. A point $I$ is equidistant from all faces. If this distance is $\frac{m\sqrt{n}}{p}$, find $m+n+p$.

Budget: 900.00 seconds | Deadline: 1772765539.46

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             4231             5              0    0.642     104
1        8             4427             7              0    0.572     104
2        3             4634             9              0    0.490     104
3        6             4992             7              0    0.512     104
4        2             6102             8              0    0.544     104

UNANIMOUS ANSWER: 104


[Problem 18 Result]
Model Predicted: 104
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 19
Statement: Triangle $ABC$ is inscribed in $\omega$. Tangents to $\omega$ at $B, C$ intersect at $D$. $AD$ intersects $\omega$ at $P$. If $AB=5, BC=9, AC=10$, and $AP=m/n$, find $m+n$.
Ground Truth Answer: 113
--------------------------------------------------

Problem: Triangle $ABC$ is inscribed in $\omega$. Tangents to $\omega$ at $B, C$ intersect at $D$. $AD$ intersects $\omega$ at $P$. If $AB=5, BC=9, AC=10$, and $AP=m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1772765596.74

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             3877            11              0    0.544     113
1        2             4519             9              0    0.670     113
2        6             5640            12              0    0.585     113
3        7             6853            13              0    0.718     113
4        5            12673            28              0    0.664     113

UNANIMOUS ANSWER: 113


[Problem 19 Result]
Model Predicted: 113
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 20
Statement: Among the 900 residents of Aimeville, 195 own a diamond ring, 367 own golf clubs, and 562 own a spade. All own candy hearts. 437 own exactly two things, and 234 own exactly three. Find the number who own all four.
Ground Truth Answer: 73
--------------------------------------------------

Problem: Among the 900 residents of Aimeville, 195 own a diamond ring, 367 own golf clubs, and 562 own a spade. All own candy hearts. 437 own exactly two things, and 234 own exactly three. Find the number who own all four.

Budget: 900.00 seconds | Deadline: 1772765706.43

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             1201             0              0    0.610      73
1        6             2244             1              1    0.596      73
2        8             3119             0              0    0.541      73
3        5             3133             1              0    0.464      73
4        2             3149             0              0    0.607      73

UNANIMOUS ANSWER: 73


[Problem 20 Result]
Model Predicted: 73
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 21
Statement: A list of positive integers has sum 30 and unique mode 9. The median is a positive integer that does not appear in the list. Find the sum of the squares of all items in the list.
Ground Truth Answer: 236
--------------------------------------------------

Problem: A list of positive integers has sum 30 and unique mode 9. The median is a positive integer that does not appear in the list. Find the sum of the squares of all items in the list.

Budget: 900.00 seconds | Deadline: 1772765735.99

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             1820             3              0    0.727     236
1        3             1922             2              0    0.772     236
2        5             1932             3              0    0.674     236
3        1             2388             4              0    0.848     236
4        8             2421             3              0    0.742     236

UNANIMOUS ANSWER: 236


[Problem 21 Result]
Model Predicted: 236
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 22
Statement: Find the number of ways to place a digit in each cell of a $2 \times 3$ grid so the sum of the two 3-digit numbers reading left to right is 999, and the sum of the three 2-digit numbers reading top to bottom is 99.
Ground Truth Answer: 236
--------------------------------------------------

Problem: Find the number of ways to place a digit in each cell of a $2 \times 3$ grid so the sum of the two 3-digit numbers reading left to right is 999, and the sum of the three 2-digit numbers reading top to bottom is 99.

Budget: 900.00 seconds | Deadline: 1772765759.57

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1             2645             1              0    0.679      21
1        4             3891             1              0    0.679      21
2        2             3916             1              0    0.622      21
3        7             4539             2              0    0.751      21
4        8             4831             2              0    0.613      21

UNANIMOUS ANSWER: 21


[Problem 22 Result]
Model Predicted: 21
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 23
Statement: Positive real numbers $x, y, z$ satisfy $\log_2(x/yz)=1/2$, $\log_2(y/xz)=1/3$, and $\log_2(z/xy)=1/4$. If $|\log_2(x^4 y^3 z^2)| = m/n$, find $m+n$.
Ground Truth Answer: 33
--------------------------------------------------

Problem: Positive real numbers $x, y, z$ satisfy $\log_2(x/yz)=1/2$, $\log_2(y/xz)=1/3$, and $\log_2(z/xy)=1/4$. If $|\log_2(x^4 y^3 z^2)| = m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1772765804.12

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1             1394             2              0    0.384      33
1        3             1448             3              0    0.434      33
2        2             1458             1              0    0.390      33
3        8             1664             2              0    0.381      33
4        6             1949             0              0    0.302      33

UNANIMOUS ANSWER: 33


[Problem 23 Result]
Model Predicted: 33
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 24
Statement: Hexagon $ABCDEF$ is convex equilateral with opposite sides parallel. Side extensions of $AB, CD, EF$ form a triangle with side lengths 200, 240, and 300. Find the side length of the hexagon.
Ground Truth Answer: 80
--------------------------------------------------

Problem: Hexagon $ABCDEF$ is convex equilateral with opposite sides parallel. Side extensions of $AB, CD, EF$ form a triangle with side lengths 200, 240, and 300. Find the side length of the hexagon.

Budget: 900.00 seconds | Deadline: 1772765821.83

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             1238             4              0    0.539      55
1        8             1493             1              0    0.647      55
2        5             1569             3              0    0.567      55
3        3             1623             4              0    0.770      55
4        1             2007             3              0    0.774      55

UNANIMOUS ANSWER: 55


[Problem 25 Result]
Model Predicted: 55
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 26
Statement: Let $N$ be the greatest four-digit integer such that whenever one digit is changed to 1, the result is divisible by 7. If $Q$ and $R$ are the quotient and remainder when $N$ is divided by 1000, find $Q+R$.
Ground Truth Answer: 699
--------------------------------------------------

Problem: Let $N$ be the greatest four-digit integer such that whenever one digit is changed to 1, the result is divisible by 7. If $Q$ and $R$ are the quotient and remainder when $N$ is divided by 1000, find $Q+R$.

Budget: 900.00 seconds | Deadline: 1772766082.47

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             1380             1              0    0.642     699
1        4             3455             3              0    0.505     699
2        7             4223             5              0    0.527     699
3        6             4515             1              0    0.545     699
4        5             4610             1              0    0.554     699

UNANIMOUS ANSWER: 699


[Problem 26 Result]
Model Predicted: 699
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 27
Statement: Find the number of triples of nonnegative integers $(a, b, c)$ satisfying $a + b + c = 300$ and $a^2 b + a^2 c + b^2 a + b^2 c + c^2 a + c^2 b = 6,000,000$.
Ground Truth Answer: 601
--------------------------------------------------

Problem: Find the number of triples of nonnegative integers $(a, b, c)$ satisfying $a + b + c = 300$ and $a^2 b + a^2 c + b^2 a + b^2 c + c^2 a + c^2 b = 6,000,000$.

Budget: 900.00 seconds | Deadline: 1772766125.41

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             4357             9              0    0.574     601
1        8             5224             5              0    0.590     601
2        5             5419             2              0    0.508     601
3        1             6150            10              0    0.591     601
4        3             6626             5              0    0.547     601

UNANIMOUS ANSWER: 601


[Problem 27 Result]
Model Predicted: 601
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 28
Statement: Let $b \geq 2$. Call a positive integer $b$-eautiful if it has exactly two digits in base $b$ that sum to $\sqrt{n}$. Find the least integer $b$ for which there are more than ten $b$-eautiful integers.
Ground Truth Answer: 211
--------------------------------------------------

Problem: Let $b \geq 2$. Call a positive integer $b$-eautiful if it has exactly two digits in base $b$ that sum to $\sqrt{n}$. Find the least integer $b$ for which there are more than ten $b$-eautiful integers.

Budget: 900.00 seconds | Deadline: 1772766186.93

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             5299             4              0    0.644     211
1        1             5692             5              0    0.677     211
2        5             5943            11              0    0.675     211
3        6             6716             4              0    0.662     211
4        4             7420            10              0    0.680     211

UNANIMOUS ANSWER: 211


[Problem 28 Result]
Model Predicted: 211
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 29
Statement: Find the number of rectangles formed inside a regular 12-gon where each side lies on either a side or a diagonal of the dodecagon.
Ground Truth Answer: 315
--------------------------------------------------

Problem: Find the number of rectangles formed inside a regular 12-gon where each side lies on either a side or a diagonal of the dodecagon.

Budget: 900.00 seconds | Deadline: 1772766257.26

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             3151             1              0    0.812      15
1        5            24076            22              2    0.708      27
2        1            25661            15              0    0.740      27
3        4            25684            31              2    0.775      27
4        6            26492            29              1    0.787      39
5        7            32704            30              2    0.793      27
6        3            37220            40              3    0.666     315
7        8            49662            50              3    0.688     315

UNANIMOUS ANSWER: 27


[Problem 29 Result]
Model Predicted: 27
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 30
Statement: Five men and nine women stand in a circle. The probability that every man stands diametrically opposite a woman is $m/n$. Find $m+n$.
Ground Truth Answer: 191
--------------------------------------------------

Problem: Five men and nine women stand in a circle. The probability that every man stands diametrically opposite a woman is $m/n$. Find $m+n$.

Budget: 900.00 seconds | Deadline: 1772766688.84

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             2549             2              0    0.785     191
1        7             2166             5              0    0.775     191
2        1             2838             3              0    0.812     191
3        8             3235             8              0    0.768     191
4        5             3780             4              0    0.871     191

UNANIMOUS ANSWER: 191


[Problem 30 Result]
Model Predicted: 191
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 31
Statement: Real numbers $b \neq 1$ and $n$ satisfy $\sqrt{\log_b n} = \log_b \sqrt{n}$ and $b \cdot \log_b n = \log_b (bn)$. If $n=j/k$, find $j+k$.
Ground Truth Answer: 881
--------------------------------------------------

Problem: Real numbers $b \neq 1$ and $n$ satisfy $\sqrt{\log_b n} = \log_b \sqrt{n}$ and $b \cdot \log_b n = \log_b (bn)$. If $n=j/k$, find $j+k$.

Budget: 900.00 seconds | Deadline: 1772766723.44

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             1167             1              0    0.677     881
1        2             1201             0              0    0.571     881
2        8             1201             0              0    0.672     881
3        4             1288             0              0    0.662     881
4        1             1401             0              0    0.583     881

UNANIMOUS ANSWER: 881


[Problem 31 Result]
Model Predicted: 881
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 32
Statement: A plane contains 40 lines, no 2 parallel. There are points where 3, 4, 5, or 6 lines intersect. Find the number of points where exactly 2 lines intersect.
Ground Truth Answer: 607
--------------------------------------------------

Problem: A plane contains 40 lines, no 2 parallel. There are points where 3, 4, 5, or 6 lines intersect. Find the number of points where exactly 2 lines intersect.

Budget: 900.00 seconds | Deadline: 1772766740.64

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             3601             0              0    0.750     746
1        7             6201             0              0    0.768     746
2        1             7282             2              0    0.725     746
3        6             9392             0              0    0.808     746
4        3            10201             0              0    0.724     746

UNANIMOUS ANSWER: 746


[Problem 32 Result]
Model Predicted: 746
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 33
Statement: The sum of all positive integers $m$ such that $13!/m$ is a perfect square is $2^a 3^b 5^c 7^d 11^e 13^f$. Find $a+b+c+d+e+f$.
Ground Truth Answer: 12
--------------------------------------------------

Problem: The sum of all positive integers $m$ such that $13!/m$ is a perfect square is $2^a 3^b 5^c 7^d 11^e 13^f$. Find $a+b+c+d+e+f$.

Budget: 900.00 seconds | Deadline: 1772766832.41

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        3             1705             6              0    0.480      12
1        5             2035             4              0    0.427      12
2        4             2032             6              0    0.488      12
3        1             2531             3              0    0.513      12
4        2             2590             3              0    0.471      12

UNANIMOUS ANSWER: 12


[Problem 33 Result]
Model Predicted: 12
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 34
Statement: Point $P$ is on the circumcircle of square $ABCD$ such that $PA \cdot PC = 56$ and $PB \cdot PD = 90$. Find the area of the square.
Ground Truth Answer: 106
--------------------------------------------------

Problem: Point $P$ is on the circumcircle of square $ABCD$ such that $PA \cdot PC = 56$ and $PB \cdot PD = 90$. Find the area of the square.

Budget: 900.00 seconds | Deadline: 1772766857.42

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4             1856             3              0    0.505     106
1        7             2620             1              0    0.575     106
2        1             2984             5              1    0.544     106
3        8             3563             0              0    0.518     106
4        3             3859             4              0    0.489     106

UNANIMOUS ANSWER: 106


[Problem 34 Result]
Model Predicted: 106
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 35
Statement: Alice knows 3 red and 3 black cards revealed in random order. Alice guesses color before each. If playing optimally, the expected correct guesses is $m/n$. Find $m+n$.
Ground Truth Answer: 51
--------------------------------------------------

Problem: Alice knows 3 red and 3 black cards revealed in random order. Alice guesses color before each. If playing optimally, the expected correct guesses is $m/n$. Find $m+n$.

Budget: 900.00 seconds | Deadline: 1772766892.93

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             2278             3              0    0.782      51
1        5             2433             3              1    0.773      51
2        7             2628             4              1    0.500      51
3        1             2635             7              1    0.577      51
4        8             3323             5              0    0.657      51

UNANIMOUS ANSWER: 51


[Problem 35 Result]
Model Predicted: 51
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 36
Statement: Call a positive integer extra-distinct if remainders when divided by 2, 3, 4, 5, and 6 are distinct. Find the number of extra-distinct positive integers less than 1000.
Ground Truth Answer: 49
--------------------------------------------------

Problem: Call a positive integer extra-distinct if remainders when divided by 2, 3, 4, 5, and 6 are distinct. Find the number of extra-distinct positive integers less than 1000.

Budget: 900.00 seconds | Deadline: 1772766925.46

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             1640             3              0    0.703      49
1        3             2919             5              0    0.731      49
2        8             3908             7              1    0.549      49
3        5             4187             4              0    0.717      49
4        2             6213            12              1    0.512      49

UNANIMOUS ANSWER: 49


[Problem 36 Result]
Model Predicted: 49
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 37
Statement: Find the number of cubic polynomials $x^3+ax^2+bx+c$ with $a,b,c \in \{-20, \dots, 20\}$ such that there is a unique integer $m \neq 2$ with $p(m)=p(2)$.
Ground Truth Answer: 738
--------------------------------------------------

Problem: Find the number of cubic polynomials $x^3+ax^2+bx+c$ with $a,b,c \in \{-20, \dots, 20\}$ such that there is a unique integer $m \neq 2$ with $p(m)=p(2)$.

Budget: 900.00 seconds | Deadline: 1772766980.44

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             5340             4              0    0.680     738
1        1             7090             6              0    0.623     738
2        6             7813             8              0    0.749     738
3        3             7683             6              0    0.617     738
4        4             7898             7              0    0.681     738

UNANIMOUS ANSWER: 738


[Problem 37 Result]
Model Predicted: 738
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 38
Statement: Find $a+U$ for the unique $a$ where $U = \sum_{n=1}^{2023} \lfloor (n^2-na)/5 \rfloor$ is an integer strictly between -1000 and 1000.
Ground Truth Answer: 944
--------------------------------------------------

Problem: Find $a+U$ for the unique $a$ where $U = \sum_{n=1}^{2023} \lfloor (n^2-na)/5 \rfloor$ is an integer strictly between -1000 and 1000.

Budget: 900.00 seconds | Deadline: 1772767058.37

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             4547             8              0    0.655     944
1        5             5336            10              0    0.635     944
2        7             5747            13              0    0.780     944
3        1             6542             4              0    0.696     944
4        3             6170             9              2    0.529     944

UNANIMOUS ANSWER: 944


[Problem 38 Result]
Model Predicted: 944
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 39
Statement: Each face of two noncongruent parallelepipeds is a rhombus with diagonals $\sqrt{21}$ and $\sqrt{31}$. If the volume ratio is $m/n$, find $m+n$.
Ground Truth Answer: 125
--------------------------------------------------

Problem: Each face of two noncongruent parallelepipeds is a rhombus with diagonals $\sqrt{21}$ and $\sqrt{31}$. If the volume ratio is $m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1772767128.59

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1             4316             2              0    0.697     125
1        4             6798             5              0    0.659     125
2        5             6799            12              0    0.594     125
3        7             8587             3              0    0.812     125
4        2             8782             4              0    0.639     125

UNANIMOUS ANSWER: 125


[Problem 39 Result]
Model Predicted: 125
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 40
Statement: Find the greatest integer less than 1000 that is a palindrome in both base 10 and base 8.
Ground Truth Answer: 585
--------------------------------------------------

Problem: Find the greatest integer less than 1000 that is a palindrome in both base 10 and base 8.

Budget: 900.00 seconds | Deadline: 1772767210.11

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        4              925             4              0    0.679     585
1        7             1350            10              0    0.617     585
2        3             1480             4              0    0.686     585
3        6             1548             9              0    0.653     585
4        2             2109             6              0    0.627     585

UNANIMOUS ANSWER: 585


[Problem 40 Result]
Model Predicted: 585
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 41
Statement: A region is formed by three unit squares in an L-shape. Two points are chosen randomly. Find $m+n$ if the probability their midpoint is inside the region is $m/n$.
Ground Truth Answer: 35
--------------------------------------------------

Problem: A region is formed by three unit squares in an L-shape. Two points are chosen randomly. Find $m+n$ if the probability their midpoint is inside the region is $m/n$.

Budget: 900.00 seconds | Deadline: 1772767230.56

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             6705             3              0    0.609      35
1        1             7638             4              0    0.636      35
2        6             8738             3              0    0.625      35
3        4             9954             2              0    0.638      35
4        7            10566             3              0    0.654      35

UNANIMOUS ANSWER: 35


[Problem 41 Result]
Model Predicted: 35
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 42
Statement: Each vertex of a regular 12-gon is colored red or blue. Find the number of colorings where no four vertices of the same color form a rectangle.
Ground Truth Answer: 928
--------------------------------------------------

Problem: Each vertex of a regular 12-gon is colored red or blue. Find the number of colorings where no four vertices of the same color form a rectangle.

Budget: 900.00 seconds | Deadline: 1772767328.23

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        7             1965             1              0    0.782     928
1        8             2122             2              0    0.817     928
2        4             2871             1              0    0.790     928
3        5             3165             1              0    0.798     928
4        3             4263             1              0    0.737     928

UNANIMOUS ANSWER: 928


[Problem 42 Result]
Model Predicted: 928
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 43
Statement: Let $\omega$ be a 7th root of unity. Find the value of the product $\prod_{k=0}^6 (\omega^{3k} + \omega^k + 1)$.
Ground Truth Answer: 24
--------------------------------------------------

Problem: Let $\omega$ be a 7th root of unity. Find the value of the product $\prod_{k=0}^6 (\omega^{3k} + \omega^k + 1)$.

Budget: 900.00 seconds | Deadline: 1772767364.81

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        5             1389             3              0    0.688    <NA>
1        1             1453             3              0    0.653      24
2        3             3149             5              1    0.694      24
3        8             3203             5              0    0.712      24
4        6             3731             6              0    0.652      24
5        4             4745             3              0    0.489      24

UNANIMOUS ANSWER: 24


[Problem 43 Result]
Model Predicted: 24
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 44
Statement: Circles $\omega_1, \omega_2$ intersect at $P, Q$. Parallel line $AB$ through $P$ forms trapezoid $XABY$. If $PX=10, PY=14, PQ=5$, find $m+n$ if the area is $m\sqrt{n}$.
Ground Truth Answer: 33
--------------------------------------------------

Problem: Circles $\omega_1, \omega_2$ intersect at $P, Q$. Parallel line $AB$ through $P$ forms trapezoid $XABY$. If $PX=10, PY=14, PQ=5$, find $m+n$ if the area is $m\sqrt{n}$.

Budget: 900.00 seconds | Deadline: 1772767405.30

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8            29383            14              1    0.675      21
1        3            32005            41              1    0.656     804
2        5            41675             5              0    0.785      72
3        4            43270            18              0    0.682      21
4        7            42339            51              6    0.726      62
5        6            53727            50              1    0.670     250
6        1            59573            48              2    0.569      33
7        2            61882            65              2    0.557    <NA>

   Answer  Votes  Score
0      21      2  2.949
1      33      1  1.756
2     804      1  1.524
3     250      1  1.493
4      62      1  1.378
5      72      1  1.274

Final Answer: 21


[Problem 44 Result]
Model Predicted: 21
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 45
Statement: For positive integer $n$, let $a_n$ be the least multiple of 23 with $a_n \equiv 1 \pmod{2^n}$. Find the number of $n \leq 1000$ such that $a_n = a_{n+1}$.
Ground Truth Answer: 363
--------------------------------------------------

Problem: For positive integer $n$, let $a_n$ be the least multiple of 23 with $a_n \equiv 1 \pmod{2^n}$. Find the number of $n \leq 1000$ such that $a_n = a_{n+1}$.

Budget: 900.00 seconds | Deadline: 1772768030.24

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             5768             8              0    0.648     363
1        5             6741             4              0    0.627     363
2        1             7135             7              0    0.601     363
3        2             8493             5              0    0.565     363
4        7             8404            17              0    0.646     363

UNANIMOUS ANSWER: 363


[Problem 45 Result]
Model Predicted: 363
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 46
Statement: Right square pyramid volume 54 has base side 6. If vertices lie on a sphere of radius $m/n$, find $m+n$.
Ground Truth Answer: 21
--------------------------------------------------

Problem: Right square pyramid volume 54 has base side 6. If vertices lie on a sphere of radius $m/n$, find $m+n$.

Budget: 900.00 seconds | Deadline: 1772768111.86

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        1             1001             0              0    0.570      21
1        8             1187             0              0    0.560      21
2        2             1430             1              0    0.663      21
3        5             1543             1              0    0.691      21
4        6             1564             2              0    0.654      21

UNANIMOUS ANSWER: 21


[Problem 46 Result]
Model Predicted: 21
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 47
Statement: Find the least value of $a+b$ for real $a>4, b>1$ satisfying $x^2/a^2 + y^2/(a^2-16) = (x-20)^2/(b^2-1) + (y-11)^2/b^2 = 1$.
Ground Truth Answer: 23
--------------------------------------------------

Problem: Find the least value of $a+b$ for real $a>4, b>1$ satisfying $x^2/a^2 + y^2/(a^2-16) = (x-20)^2/(b^2-1) + (y-11)^2/b^2 = 1$.

Budget: 900.00 seconds | Deadline: 1772768125.96

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        6             8714             4              0    0.565      23
1        5            12552            11              0    0.670      23
2        8            16195            16              4    0.663      23
3        2            20699            17              6    0.524      23
4        3            24970            13              1    0.500      23

UNANIMOUS ANSWER: 23


[Problem 47 Result]
Model Predicted: 23
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 48
Statement: Twenty points on a circle are labeled 1-20. Segments are drawn between points whose labels differ by a prime. Find the number of triangles formed.
Ground Truth Answer: 72
--------------------------------------------------

Problem: Twenty points on a circle are labeled 1-20. Segments are drawn between points whose labels differ by a prime. Find the number of triangles formed.

Budget: 900.00 seconds | Deadline: 1772768367.16

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             2335             2              0    0.794      72
1        5             2741             1              0    0.822      72
2        3             2778             2              0    0.742      72
3        6             2869             2              0    0.771      72
4        4             3496             2              0    0.729      72

UNANIMOUS ANSWER: 72


[Problem 48 Result]
Model Predicted: 72
Status: ✅ CORRECT
==================================================

==================================================
TESTING PROBLEM 49
Statement: Find the remainder when $N$ is divided by 1000, where $N$ is the number of sequences of 144 independent hand movements on an analog clock returning to 12.
Ground Truth Answer: 608
--------------------------------------------------

Problem: Find the remainder when $N$ is divided by 1000, where $N$ is the number of sequences of 144 independent hand movements on an analog clock returning to 12.

Budget: 900.00 seconds | Deadline: 1772768399.14

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        2             3375             6              0    0.894     528
1        5             3861             3              0    0.907     950
2        4             4392             6              0    0.801     950
3        1             4470             4              0    0.899     950
4        6             5382             5              0    0.892     950
5        3             5849             4              0    0.740     950

UNANIMOUS ANSWER: 950


[Problem 49 Result]
Model Predicted: 950
Status: ❌ INCORRECT
==================================================

==================================================
TESTING PROBLEM 50
Statement: What is the maximum number of terms in an arithmetic sequence of primes with a common difference of 6?
Ground Truth Answer: 5
--------------------------------------------------

Problem: What is the maximum number of terms in an arithmetic sequence of primes with a common difference of 6?

Budget: 900.00 seconds | Deadline: 1772768452.07

   Attempt  Response Length  Python Calls  Python Errors  Entropy  Answer
0        8             1401             0              0    0.839       5
1        6             1601             0              0    0.899       5
2        3             2122             0              0    0.874       5
3        2             2401             0              0    0.887       5
4        1             2536             2              0    0.772       5

UNANIMOUS ANSWER: 5


[Problem 50 Result]
Model Predicted: 5
Status: ✅ CORRECT
==================================================

    idx  prediction  ground_truth  correct
0    17         197           540    False
1    18         104           197    False
2    19         113           113     True
3    20          73            73     True
4    21         236           236     True
5    22          21           236    False
6    23          33            33     True
7    24          80            80     True
8    25          55            55     True
9    26         699           699     True
10   27         601           601     True
11   28         211           211     True
12   29          27           315    False
13   30         191           191     True
14   31         881           881     True
15   32         746           607    False
16   33          12            12     True
17   34         106           106     True
18   35          51            51     True
19   36          49            49     True
20   37         738           738     True
21   38         944           944     True
22   39         125           125     True
23   40         585           585     True
24   41          35            35     True
25   42         928           928     True
26   43          24            24     True
27   44          21            33    False
28   45         363           363     True
29   46          21            21     True
30   47          23            23     True
31   48          72            72     True
32   49         950           608    False
33   50           5             5     True

Accuracy (problems 17–50): 79.41%